### ISSUE TITLE
Max speed SPI as DMA slave

### ISSUE THREAD

**Issue by PAk-CatchFire** [hideakitai/ESP32DMASPI#1]
Hello,  and thank you for this amazing library.
Which is the max speed you get with this setup as slave? Is it the 80Mhz max. stated in the Documentation?

Thank you

**Comment by hideakitai** [comment]
@PAk-CatchFire Sorry for late reply! The speed of SPI is mentioned [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_slave.html#sclk-frequency-requirements). 80MHz is the maximum speed of GPIO_MUX itself.
