### ISSUE TITLE
40 & 80MHz not work

### ISSUE THREAD

**Issue by Scadi2** [hideakitai/ESP32DMASPI#29]
Up to a frequency of 26,666,666Hz (80Mhz/3) it works perfectly.
at 40 & 80MHz this error appears:
[ERROR] SPI device transmit failed : 258
E (26712) spi_master: check_trans_valid(676): invalid dev handle

I need 80MHZ for a high-speed application.

**Comment by hideakitai** [comment]
You can if you make a correctly routed PCB. For example, 8MHz is too fast for the breadboard.

```cpp
master.setFrequency(4000000);            // default: 8MHz (too fast for bread board...)
```

FYI

https://www.protoexpress.com/blog/best-high-speed-pcb-routing-practices/
