### ISSUE TITLE
is master write blocking until all buffer sent?

### ISSUE THREAD

**Issue by mark-hahn** [hideakitai/ESP32DMASPI#3]
Is master write blocking until all buffer sent?   Isn't the point of dma to be able to use it in background while doing other things?

**Comment by hideakitai** [comment]
@mark-hahn Hi, you can use non-blocking send by `queue()`

**Comment by mark-hahn** [comment]
Thanks -- I missed that.

**Comment by hideakitai** [comment]
Maybe I should improve README and examples.

**Comment by brahma-dev** [comment]
@hideakitai It seems like queue() only works if I yield() at some point. I am very new to this so probably doing something wrong.

**Comment by hideakitai** [comment]
@brahma-dev @mark-hahn  Ah, sorry for that. You should wait until the transaction ends when using `transfer()` or `queue()` + `yield()`. No API can complete transactions asynchronously (in the background).

See the official API reference for more details.
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/spi_master.html#api-reference-spi-master
