### ISSUE TITLE
SINUS_TABLE

### ISSUE THREAD

**Issue by AntonioRiccelli77** [hideakitai/ESP32DMASPI#52]
I'm continuing the tests on the MAX542 DAC but I can't get a functional result with DMA.
In summary. I have to send from an ESP32 Master a table of at least 32 16-bit values sent as MSB + LSB pairs (MSB FIRST) in the fastest possible way because I am interested in reaching 300Khz output to the DAC, however this does not happen with the standard method I can't get above 8Khz. Here is the code:

this is a sinus.h
``
#define TABLE_SIZE 32

uint16_t sinus[TABLE_SIZE]={

0x8000, 0x98f8, 0xb0fb, 0xc71c, 0xda82, 0xea6d, 0xf641, 0xfd89,
0xffff, 0xfd89, 0xf641, 0xea6d, 0xda82, 0xc71c, 0xb0fb, 0x98f8,
0x8000, 0x6707, 0x4f04, 0x38e3, 0x257d, 0x1592, 0x9be, 0x276,
0x00, 0x276, 0x9be, 0x1592, 0x257d, 0x38e3, 0x4f04, 0x6707

};

``

this is a MAX542.h
`
#include <ESP32DMASPIMaster.h>
#include "helper.h"
#include "sinus.h"

ESP32DMASPI::Master master;

static constexpr size_t BUFFER_SIZE = TABLE_SIZE*2; // should be multiple of 4
static constexpr size_t QUEUE_SIZE = 1;
uint8_t *dma_tx_buf;
uint8_t *dma_rx_buf;

SPIClass *hspi = NULL;

const int slaveSelectPin = 15;

void initMAX542() {
    
  
    
       
    // to use DMA buffer, use these methods to allocate buffer
    dma_tx_buf = master.allocDMABuffer(BUFFER_SIZE);
    //dma_rx_buf = master.allocDMABuffer(BUFFER_SIZE);
    master.setDataMode(SPI_MODE0);           // default: SPI_MODE0
    master.setFrequency(10000000);            // default: 8MHz (too fast for bread board...)
    master.setMaxTransferSize(BUFFER_SIZE);  // default: 4092 bytes
    master.setQueueSize(QUEUE_SIZE);         // default: 1
    
    // begin() after setting
    master.begin();  // default: HSPI (CS: 15, CLK: 14, MOSI: 13, MISO: 12)

    
    for(size_t i=0;i< TABLE_SIZE; i++){
        
        dma_tx_buf[i]=highByte(sinus[i]);
        
        dma_tx_buf[i+1]=lowByte(sinus[i]);

        Serial.print(dma_tx_buf[i]);
        
    }

    delay(2000);

    Serial.println("start spi master");
    
  
 

}

void setMAX542(){
    
     // start and wait to complete one BIG transaction (same data will be received from slave)
     const size_t received_bytes = master.transfer(dma_tx_buf, NULL, BUFFER_SIZE);
         
  
    
}
`

this is a main.cpp
`
void setup{

  initMAX542();

}

void loop() {

   setMAX542();

}
`

**Comment by hideakitai** [comment]
Could you format your codes correctly?

**Comment by AntonioRiccelli77** [comment]
[code.zip](https://github.com/hideakitai/ESP32DMASPI/files/14623422/code.zip)

**Comment by hideakitai** [comment]
I cannot use my computer for a while, so I would like you to make it easier to view from my cell phone...

**Comment by AntonioRiccelli77** [comment]
main.cpp [https://pastebin.com/embed_js/E3c38sfF](url)
sinus.h [https://pastebin.com/embed_js/RhKs16GE](url)
MAX542.h [https://pastebin.com/embed_js/Fcccc9MP](url)

**Comment by AntonioRiccelli77** [comment]
SPI
<img width="1036" alt="Cattura2" src="https://github.com/hideakitai/ESP32DMASPI/assets/63198686/7f52cfba-4259-418d-8108-5e4f4814d96e">

SPI DMA
<img width="1039" alt="Cattura" src="https://github.com/hideakitai/ESP32DMASPI/assets/63198686/b9b0f13b-d14f-494e-8191-d7b873a471dc">

**Comment by AntonioRiccelli77** [comment]
if it worked, I would also like to know how to introduce a delay of a few microseconds between one transaction and the next so as not to exceed the slave's ability to receive data not very quickly

**Comment by hideakitai** [comment]
I can't see the link when I open it in my browser…

**Comment by hideakitai** [comment]
Also, what is your problem? It also works with DMA but requires more speed? Or DMA SPI doesn't work at all?

**Comment by AntonioRiccelli77** [comment]
[MAX542.h.pdf](https://github.com/hideakitai/ESP32DMASPI/files/14624134/MAX542.h.pdf)
<img width="391" alt="sinus" src="https://github.com/hideakitai/ESP32DMASPI/assets/63198686/bd981079-9d9d-4c14-a196-f5af23aae5fd">
<img width="367" alt="main" src="https://github.com/hideakitai/ESP32DMASPI/assets/63198686/57870b60-42d4-419d-91e8-bc3956601b90">

**Comment by AntonioRiccelli77** [comment]
<img width="367" alt="main" src="https://github.com/hideakitai/ESP32DMASPI/assets/63198686/63e9e2d9-e78b-405e-af2d-bc96f9b458c6">
<img width="391" alt="sinus" src="https://github.com/hideakitai/ESP32DMASPI/assets/63198686/97748a15-2189-4b56-bed9-6cf55bce9778">
![MAX542 h_01](https://github.com/hideakitai/ESP32DMASPI/assets/63198686/69110b4c-d136-40a1-a7bb-cf6335a7390a)
![MAX542 h_02](https://github.com/hideakitai/ESP32DMASPI/assets/63198686/b9dcbdef-e6f1-4b77-b448-e3f9ac09d766)
![MAX542 h_03](https://github.com/hideakitai/ESP32DMASPI/assets/63198686/0d346cb0-76af-465e-b042-a9c5abfff5df)
![MAX542 h_04](https://github.com/hideakitai/ESP32DMASPI/assets/63198686/4e0f21bf-be62-47e8-8ecf-2487e5e5bc06)

**Comment by AntonioRiccelli77** [comment]
![MAX542 h_01](https://github.com/hideakitai/ESP32DMASPI/assets/63198686/414dfdee-d60b-4e84-bc96-957b153fda40)
![MAX542 h_02](https://github.com/hideakitai/ESP32DMASPI/assets/63198686/d1439125-7ec5-4c90-95b7-267bec8bb118)
![MAX542 h_03](https://github.com/hideakitai/ESP32DMASPI/assets/63198686/774b0251-bf24-4992-b434-e8276998201e)
![MAX542 h_04](https://github.com/hideakitai/ESP32DMASPI/assets/63198686/e91b5ebb-9c04-4272-8a1b-faea93e3884e)

**Comment by AntonioRiccelli77** [comment]
> Also, what is your problem? It also works with DMA but requires more speed? Or DMA SPI doesn't work at all?

DMA SPI doesn't work at all. in oscilloscope fotos see the problem. The output of DAC is absent in this method. DMA is too fast ?  If yes, how to introduce a delay beetween transactions?

**Comment by hideakitai** [comment]
Please refer https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by AntonioRiccelli77** [comment]
``
#include <ESP32DMASPIMaster.h>
#include "helper.h"
#include "sinus.h"
 
ESP32DMASPI::Master master;
 
static constexpr size_t BUFFER_SIZE = TABLE_SIZE*2; // should be multiple of 4
static constexpr size_t QUEUE_SIZE = 1;
uint8_t *dma_tx_buf;
uint8_t *dma_rx_buf;
 
//SPIClass *hspi = NULL;
 
const int slaveSelectPin = 15;
 
 
 
 
 
void initMAX542() {
    
  
    /*
    hspi = new SPIClass(HSPI); 
    pinMode(slaveSelectPin, OUTPUT);
        
    hspi->begin(14, 12, 13, slaveSelectPin); 
    */
    
    
    // to use DMA buffer, use these methods to allocate buffer
    dma_tx_buf = master.allocDMABuffer(BUFFER_SIZE);
    //dma_rx_buf = master.allocDMABuffer(BUFFER_SIZE);
    master.setDataMode(SPI_MODE0);           // default: SPI_MODE0
    master.setFrequency(10000000);            // default: 8MHz (too fast for bread board...)
    master.setMaxTransferSize(BUFFER_SIZE);  // default: 4092 bytes
    master.setQueueSize(QUEUE_SIZE);         // default: 1
    
    // begin() after setting
    master.begin();  // default: HSPI (CS: 15, CLK: 14, MOSI: 13, MISO: 12)
 
    
    for(size_t i=0;i< TABLE_SIZE; i++){
        
        dma_tx_buf[i]=highByte(sinus[i]);
        
        dma_tx_buf[i+1]=lowByte(sinus[i]);
 
        Serial.print(dma_tx_buf[i]);
        // copy received data to tx buffer for next transfer
        //memcpy(sinus, dma_tx_buf, BUFFER_SIZE);
 
 
    }
 
    delay(2000);
 
    Serial.println("start spi master");
    
  
 
 
}
 
 
 
/*
void setMAX542(char msb, char lsb) {
 
  
  hspi->beginTransaction(SPISettings(10000000, MSBFIRST, SPI_MODE0)); 
 
  digitalWrite(slaveSelectPin, 0); // Start of transmission: set chip select LOW
  
  
  hspi->transfer(msb);
  
  
  hspi->transfer(lsb);
 
  
  
  digitalWrite(slaveSelectPin, 1); // Start of transmission: set chip select LOW
    
 
  hspi->endTransaction();
 
  
  
}
*/
 
 
 
void setMAX542(){
 
    
    // initialize tx/rx buffers
    //initializeBuffers(dma_tx_buf, dma_rx_buf, BUFFER_SIZE);
    
    // start and wait to complete one BIG transaction (same data will be received from slave)
    
    master.transfer(dma_tx_buf, NULL, BUFFER_SIZE);
    
 
 
   /*
   for(size_t i=0;i< TABLE_SIZE; i++){
 
        
        
        
        
        hspi->beginTransaction(SPISettings(10000000, MSBFIRST, SPI_MODE0)); 
        
        
        digitalWrite(slaveSelectPin, 0); // Start of transmission: set chip select LOW
    
        
        hspi->transfer(dma_tx_buf[i]);
        
        
        
        hspi->transfer(dma_tx_buf[i+1]);
        
        
        digitalWrite(slaveSelectPin, 1); // Start of transmission: set chip select LOW
            
    
        hspi->endTransaction();
 
        //Serial.print(dma_tx_buf[i]);
       
 
 
    }
    */
 
    
 
   
  
    
}
 ``

**Comment by AntonioRiccelli77** [comment]
```C++
#include <ESP32DMASPIMaster.h>
#include "helper.h"
#include "sinus.h"
 
ESP32DMASPI::Master master;
 
static constexpr size_t BUFFER_SIZE = TABLE_SIZE*2; // should be multiple of 4
static constexpr size_t QUEUE_SIZE = 1;
uint8_t *dma_tx_buf;
uint8_t *dma_rx_buf;
 
//SPIClass *hspi = NULL;
 
const int slaveSelectPin = 15;
 
 
 
 
 
void initMAX542() {
   
 
    /*
    hspi = new SPIClass(HSPI);
    pinMode(slaveSelectPin, OUTPUT);
       
    hspi->begin(14, 12, 13, slaveSelectPin);
    */
   
   
    // to use DMA buffer, use these methods to allocate buffer
    dma_tx_buf = master.allocDMABuffer(BUFFER_SIZE);
    //dma_rx_buf = master.allocDMABuffer(BUFFER_SIZE);
    master.setDataMode(SPI_MODE0);           // default: SPI_MODE0
    master.setFrequency(10000000);            // default: 8MHz (too fast for bread board...)
    master.setMaxTransferSize(BUFFER_SIZE);  // default: 4092 bytes
    master.setQueueSize(QUEUE_SIZE);         // default: 1
   
    // begin() after setting
    master.begin();  // default: HSPI (CS: 15, CLK: 14, MOSI: 13, MISO: 12)
 
   
    for(size_t i=0;i< TABLE_SIZE; i++){
       
        dma_tx_buf[i]=highByte(sinus[i]);
       
        dma_tx_buf[i+1]=lowByte(sinus[i]);
 
        Serial.print(dma_tx_buf[i]);
        // copy received data to tx buffer for next transfer
        //memcpy(sinus, dma_tx_buf, BUFFER_SIZE);
 
 
    }
 
    delay(2000);
 
    Serial.println("start spi master");
   
 
 
 
}
 
 
 
/*
void setMAX542(char msb, char lsb) {
 
 
  hspi->beginTransaction(SPISettings(10000000, MSBFIRST, SPI_MODE0));
 
  digitalWrite(slaveSelectPin, 0); // Start of transmission: set chip select LOW
 
 
  hspi->transfer(msb);
 
 
  hspi->transfer(lsb);
 
 
 
  digitalWrite(slaveSelectPin, 1); // Start of transmission: set chip select LOW
   
 
  hspi->endTransaction();
 
 
 
}
*/
 
 
 
void setMAX542(){
 
   
    // initialize tx/rx buffers
    //initializeBuffers(dma_tx_buf, dma_rx_buf, BUFFER_SIZE);
   
    // start and wait to complete one BIG transaction (same data will be received from slave)
   
    master.transfer(dma_tx_buf, NULL, BUFFER_SIZE);
   
 
 
   /*
   for(size_t i=0;i< TABLE_SIZE; i++){
 
       
       
       
       
        hspi->beginTransaction(SPISettings(10000000, MSBFIRST, SPI_MODE0));
       
       
        digitalWrite(slaveSelectPin, 0); // Start of transmission: set chip select LOW
   
       
        hspi->transfer(dma_tx_buf[i]);
       
       
       
        hspi->transfer(dma_tx_buf[i+1]);
       
       
        digitalWrite(slaveSelectPin, 1); // Start of transmission: set chip select LOW
           
   
        hspi->endTransaction();
 
        //Serial.print(dma_tx_buf[i]);
       
 
 
    }
    */
 
   
 
   
 
   
}
 
 
```

**Comment by hideakitai** [comment]
As I said before, is MAX542 designed to receive sinus in one transaction? In case of normal SPI, it seems to send it every 2 bytes.

**Comment by AntonioRiccelli77** [comment]
MAX542 can be accept 2 byte for translation MSB+LSB for 16bit Revolution
and not over.
This Is problem for DMA ?

Il Sab 16 Mar 2024, 22:10 Hideaki Tai ***@***.***> ha scritto:

**Comment by hideakitai** [comment]
This library sends a lot of bytes in one transaction. So, if MAX542 does not accept more than 16 bits in one transaction, you should use standard SPI.

**Comment by AntonioRiccelli77** [comment]
Is possibile modify library for this device and Speed up the standard SPI ?
If you capable can pay for your help...

Il Sab 16 Mar 2024, 22:43 Hideaki Tai ***@***.***> ha scritto:

**Comment by hideakitai** [comment]
In general, if you want to increase the speed with normal SPI, you need to increase the clock speed and speed up the CS operation (do not use Arduino's digitalWrite but use native GPIO operation).

**Comment by hideakitai** [comment]
You can find many articles to speed up digitalWrite

**Comment by hideakitai** [comment]
If you really need my help, I can of course create a library (or sketch) using the ESP32 SPI API as a job. In that case, please send me an email.

**Comment by AntonioRiccelli77** [comment]
OK, I'll send you the specifications as soon as possible and give me a
financial quote for your fee for writing a custom library

Ty so much



Il Sab 16 Mar 2024, 23:18 Hideaki Tai ***@***.***> ha scritto:
