### ISSUE TITLE
1ms minimum packet time.

### ISSUE THREAD

**Issue by Artemkamax** [hideakitai/ESP32DMASPI#53]
Hi! I trying to use example "transfer_big_data_in_the_background"
sending 256bytes at 20Mhz speed from one esp32 to another as fast as i can, but as I see master send packet, and wait somesthing. now packet transfering time is 1ms. If I send 1200bytes, transfering time also 1ms. How I can change it?
I can transfer 16000 bytes in one packet, but slave cant recieve this packet, some bytes are missed. 
I need to reach at least 2 160 000Bytes/s
teoretical at 20Mhz I can 2.5Mbytes/s and 5Mbytes/s at 40Mhz, but have problems
<img width="644" alt="Screenshot 2024-03-27 152942" src="https://github.com/hideakitai/ESP32DMASPI/assets/32341053/db0f583a-1fad-4d60-8566-620eb13ca43a">
<img width="659" alt="Screenshot 2024-03-27 153054" src="https://github.com/hideakitai/ESP32DMASPI/assets/32341053/60a77757-9d76-4a6d-a2a7-31b7fb98a3d5">

**Comment by hideakitai** [comment]
It's probably FreeRTOS context switch. For more speed, we recommend writing your own code without this library.

**Comment by hideakitai** [comment]
> 1200bytes in a packet at 20mhz is maximum?

No. It may be a problem of hardware (noise, etc.)

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.
