### ISSUE TITLE
Undefined `spi_master_tx_buf` in `slave_simple_task.ino` example

### ISSUE THREAD

**Issue by e-tinkers** [hideakitai/ESP32DMASPI#8]
Hideaki san,

Thanks for the simple and easy-to-use library.

On the [slave_simple_task.ino](https://github.com/hideakitai/ESP32DMASPI/blob/master/examples/slave_simple_task/slave_simple_task.ino) example, the reference to `spi_master_tx_buf` at `set_buffer()` should be removed as it is not defined and not in use.

```
void set_buffer() {
    for (uint32_t i = 0; i < BUFFER_SIZE; i++) {
        spi_master_tx_buf[i] = i & 0xFF;
        spi_slave_tx_buf[i] = (0xFF - i) & 0xFF;
    }
    memset(spi_master_rx_buf, 0, BUFFER_SIZE);
    memset(spi_slave_rx_buf, 0, BUFFER_SIZE);
} 
```

**Comment by hideakitai** [comment]
@e-tinkers Thank you! Fixed
