### ISSUE TITLE
Something wrong

### ISSUE THREAD

**Issue by L10N37** [hideakitai/ESP32DMASPI#9]
This totally broke my ESP32, Uploading any of your examples caused a reset boot loop. I spent hours trying to fix the board using different methods of erasing the flash and trying every firmware you could possibly find. At one stage I bought it back to life, and was able to use the SD example for my VSPI SD card, then I uploaded your example again and it went back to a bootloop. Been up all night and EVERYTHING boot loops, except micropython FW.

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:5656
load:0x40078000,len:12696
load:0x40080400,len:4292
entry 0x400806b0
MicroPython v1.17 on 2021-09-02; ESP32 module with ESP32
Type "help()" for more information.
>>> 

I'm not blaming you, just a little confused as to how it's happening. I can't seem to get anything working now other than this.

**Comment by hideakitai** [comment]
@L10N37 Hi, have you installed micropython FW? This is the library for Arduino.
